import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared/navigation/Navbar";
import { NavbarLinkType } from "@/components/shared/navigation/NavbarLink";
import { Footer } from "@/components/shared/footer";
const open_sans = Open_Sans({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mainLinks: NavbarLinkType[] = [
  { name: "Search", target: "" },
  { name: "Home", target: "/" },
  { name: "About Us", target: "/about" },
  { name: "Shop", target: "/shop" },
  { name: "Services", target: "/services" },
  { name: "Contact", target: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${open_sans.className} antialiased`}>
        <Navbar links={mainLinks} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
